### ISSUE TITLE
weblate tool

### ISSUE THREAD

**Issue by foXaCe** [unraid/lang-en_US#35]
hello,

it possible to use this tools for edit the translation ?

https://hosted.weblate.org/

**Comment by spencerjunraid** [comment]
I'll check it out. For now, we are using Github and https://squidly271.github.io/languageErrors.html# to manage the translations. I also have a separate project management platform for teams.

What language are you interested in working on?

**Comment by foXaCe** [comment]
For the french translation

**Comment by spencerjunraid** [comment]
https://squidly271.github.io/languageErrors.html#fr_FR

It looks like French looks pretty good as far as translations that are currently needed. If you have edits/suggestions to the current ones, feel free to also post here: https://forums.unraid.net/forum/79-french-fran%C3%A7ais/

Many of the French translators are active in the French forum.

**Comment by foXaCe** [comment]
Ok thanks you
